name: CMake

on:
  push:
    branches: [ master package-as-lib]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: rtohid/vascular:github-workflow

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run:
        source ${{github.workspace}}/scripts/setuo-env.sh
        cmake -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}  -S . -B cmake-build/${{env.BUILD_TYPE}}
        cmake --build cmake-build/${{env.BUILD_TYPE}} --parallel
        cmake --install cmake-build/${{env.BUILD_TYPE}} --prefix cmake-install/${{env.BUILD_TYPE}} 
      # cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DHYPRE_LIBRARY=$HYPRE_DIR/libHYPRE.so -DCMAKE_CXX_FLAGS=-march=native -Dsleef_DIRECTORY=$sleef_DIR

    # - name: Build
    #   run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   run: ctest -C ${{env.BUILD_TYPE}}
