name: CMake Docker

on:
  push:
    branches: [master, alaki]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Environment Variable
        run: |
          git init VascularModelingData
          cd VascularModelingData
          git remote add origin https://github.com/STEllAR-GROUP/VascularModelingData.git
          git config core.sparsecheckout true
          echo "reference_results/single_node" >> .git/info/sparse-checkout
          git pull origin master
          ls reference_results/single_node/
